name: Update Liquidity CSV

on:
  schedule:
    - cron: '0 6 * * 1'  # Chaque lundi à 6h UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install pandas
        run: pip install pandas
      - name: Run script
        run: python generate_liquidity_csv.py
      - name: Commit and push
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add liquidity.csv
          git commit -m "Mise à jour automatique du CSV"
          git push
